default: &default  
  adapter: postgresql  
  host: 127.0.0.1  
  encoding: unicode  
  username: postgres  
  password: postgres  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  

development:  
  <<: *default  
  port: 5432  
  database: bestmen_development  

test:  
  <<: *default  
  port: 15432  
  database: bestmen_test  

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
